"""
Brick Base Class - DO NOT EDIT THIS FILE

This file contains the connection plumbing that makes bricks work.
DO NOT MODIFY - updates may overwrite your changes.

To create your brick, edit main.py instead.

What this file handles (automatically):
- TCP connection to router (port 9900)
- Message protocol (4-byte length prefix + JSON)
- Registration with router
- Command routing to your cmd_* methods
"""

import asyncio
import json
import logging
import struct
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class BrickClient:
    """
    Base class for bricks. DO NOT EDIT - extend this in main.py.
    """
    
    def __init__(self, config_path: Path = None):
        """Initialize brick from config."""
        if config_path is None:
            config_path = Path(__file__).parent / "brick.json"
        
        with open(config_path, encoding='utf-8') as f:
            self.config = json.load(f)
        
        self.brick_id = self.config.get("id", "unknown")
        self.name = self.config.get("name", "Unknown Brick")
        self.running = False
        
        # Router connection
        self.router_host = "127.0.0.1"
        self.router_port = 9900
        self.reader: Optional[asyncio.StreamReader] = None
        self.writer: Optional[asyncio.StreamWriter] = None
        
        # Parse capabilities from brick.json
        commands = self.config.get("commands", [])
        if isinstance(commands[0], dict) if commands else False:
            self.capabilities = [cmd.get("name", "") for cmd in commands]
        else:
            self.capabilities = commands
        
        logger.info(f"Loaded brick: {self.name} ({self.brick_id})")
    
    async def connect(self) -> bool:
        """Connect to the router."""
        try:
            self.reader, self.writer = await asyncio.open_connection(
                self.router_host, self.router_port
            )
            logger.info(f"Connected to router at {self.router_host}:{self.router_port}")
            return True
        except Exception as e:
            logger.error(f"Failed to connect to router: {e}")
            return False
    
    async def send_message(self, data: Dict) -> bool:
        """Send message to router."""
        if not self.writer:
            return False
        
        try:
            msg = json.dumps(data).encode('utf-8')
            length = struct.pack('>I', len(msg))
            self.writer.write(length + msg)
            await self.writer.drain()
            return True
        except Exception as e:
            logger.error(f"Send error: {e}")
            return False
    
    async def receive_message(self) -> Optional[Dict]:
        """Receive message from router."""
        if not self.reader:
            return None
        
        try:
            length_data = await self.reader.readexactly(4)
            length = struct.unpack('>I', length_data)[0]
            
            if length > 1_000_000:
                logger.warning(f"Message too large: {length}")
                return None
            
            data = await self.reader.readexactly(length)
            return json.loads(data.decode('utf-8'))
        
        except asyncio.IncompleteReadError:
            return None
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON: {e}")
            return None
        except Exception as e:
            logger.debug(f"Receive error: {e}")
            return None
    
    async def register(self) -> bool:
        """Register with router."""
        register_msg = {
            "type": "register",
            "brick_id": self.brick_id,
            "name": self.name,
            "capabilities": self.capabilities
        }
        
        if not await self.send_message(register_msg):
            return False
        
        response = await self.receive_message()
        if response and response.get("type") == "registered":
            logger.info(f"Registered with router: {response}")
            return True
        
        logger.error(f"Registration failed: {response}")
        return False
    
    async def handle_message(self, message: Dict[str, Any]) -> Dict[str, Any]:
        """Route incoming messages to cmd_* handlers."""
        msg_type = message.get("type", "")
        msg_id = message.get("id", "")
        data = message.get("data", {})
        
        if msg_type == "command":
            command = data.get("command", "")
            args = data.get("args", {})
            
            handler = getattr(self, f"cmd_{command}", None)
            if handler:
                try:
                    result = await handler(args) if asyncio.iscoroutinefunction(handler) else handler(args)
                    return {"id": msg_id, "type": "response", "success": True, "data": result}
                except Exception as e:
                    logger.exception(f"Command {command} failed")
                    return {"id": msg_id, "type": "error", "success": False, "error": str(e)}
            else:
                return {"id": msg_id, "type": "error", "success": False, "error": f"Unknown command: {command}"}
        
        elif msg_type == "ping":
            return {"id": msg_id, "type": "pong"}
        
        return {"id": msg_id, "type": "error", "success": False, "error": f"Unknown message type: {msg_type}"}
    
    async def send_update(self, update_type: str, data: Dict[str, Any]) -> bool:
        """Send progress/status update to GUI."""
        message = {
            "type": "brick_update",
            "brick_id": self.brick_id,
            "update_type": update_type,
            "data": data
        }
        return await self.send_message(message)
    
    async def run(self):
        """Main loop."""
        self.running = True
        
        if not await self.connect():
            logger.error("Could not connect to router. Is it running?")
            return
        
        if not await self.register():
            logger.error("Registration failed")
            return
        
        logger.info(f"Brick '{self.name}' ready")
        
        try:
            while self.running:
                message = await self.receive_message()
                if message is None:
                    logger.warning("Connection to router lost")
                    break
                
                response = await self.handle_message(message)
                await self.send_message(response)
        
        except asyncio.CancelledError:
            logger.info("Brick cancelled")
        except Exception as e:
            logger.exception(f"Brick error: {e}")
        finally:
            if self.writer:
                self.writer.close()
                try:
                    await self.writer.wait_closed()
                except Exception:
                    pass
            logger.info("Brick stopped")
