"""
Mod Base Class - DO NOT EDIT THIS FILE

This file contains the connection plumbing that makes mods work.
DO NOT MODIFY - updates may overwrite your changes.

To create your mod, edit main.py instead.

What this file handles (automatically):
- TCP connection to router (port 9900)
- Message protocol (4-byte length prefix + JSON)
- Registration with router
- Command routing to your cmd_* methods

Threading model:
- Both ModClient and ModRouter use synchronous sockets + threading.
- Each mod runs in its own subprocess — blocking I/O is fine.
- cmd_* handlers are plain synchronous methods.
"""

import json
import logging
import socket
import struct
import threading
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class ModClient:
    """
    Base class for mods. DO NOT EDIT — extend this in main.py.

    Uses synchronous sockets and threading to match the ModRouter.
    """

    def __init__(self, config_path: Optional[Path] = None):
        """Initialize mod from config."""
        if config_path is None:
            config_path = Path(__file__).parent / "mod.json"

        with open(config_path, encoding="utf-8") as f:
            self.config = json.load(f)

        self.mod_id: str = self.config.get("id", "unknown")
        self.name: str = self.config.get("name", "Unknown Mod")
        self.running = False

        # Router connection
        self.router_host = "127.0.0.1"
        self.router_port = 9900
        self._socket: Optional[socket.socket] = None
        self._send_lock = threading.Lock()

        # Parse capabilities from mod.json
        commands = self.config.get("commands", [])
        if commands and isinstance(commands[0], dict):
            self.capabilities = [cmd.get("name", "") for cmd in commands]
        else:
            self.capabilities = list(commands)

        logger.info(f"Loaded mod: {self.name} ({self.mod_id})")

    # =========================================================================
    # NETWORK PROTOCOL  (sync sockets, matches ModRouter)
    # =========================================================================

    def connect(self) -> bool:
        """Connect to the router via TCP."""
        try:
            self._socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._socket.connect((self.router_host, self.router_port))
            self._socket.settimeout(120.0)  # 2× heartbeat interval
            logger.info(f"Connected to router at {self.router_host}:{self.router_port}")
            return True
        except Exception as e:
            logger.error(f"Failed to connect to router: {e}")
            self._socket = None
            return False

    def send_message(self, data: Dict) -> bool:
        """Send a length-prefixed JSON message to the router."""
        if not self._socket:
            return False
        try:
            msg = json.dumps(data).encode("utf-8")
            length = struct.pack(">I", len(msg))
            with self._send_lock:
                self._socket.sendall(length + msg)
            return True
        except Exception as e:
            logger.error(f"Send error: {e}")
            return False

    def receive_message(self) -> Optional[Dict]:
        """Receive a length-prefixed JSON message.

        Returns the parsed dict, or *None* on disconnect.
        Raises ``socket.timeout`` when no data arrives within the
        timeout window so the caller can decide whether to retry.
        """
        if not self._socket:
            return None
        try:
            length_data = self._recv_exact(4)
            if not length_data:
                return None  # Remote side closed

            length = struct.unpack(">I", length_data)[0]

            if length > 10_000_000:  # 10 MB safety limit
                logger.warning(f"Message too large: {length}")
                return None

            data = self._recv_exact(length)
            if not data:
                return None

            return json.loads(data.decode("utf-8"))
        except socket.timeout:
            raise  # Propagate so run() can retry
        except json.JSONDecodeError as e:
            logger.error(f"Invalid JSON: {e}")
            return None
        except Exception as e:
            logger.debug(f"Receive error: {e}")
            return None

    def _recv_exact(self, n: int) -> Optional[bytes]:
        """Read exactly *n* bytes from the socket."""
        buf = b""
        while len(buf) < n:
            chunk = self._socket.recv(n - len(buf))
            if not chunk:
                return None  # Connection closed
            buf += chunk
        return buf

    # =========================================================================
    # REGISTRATION
    # =========================================================================

    def register(self) -> bool:
        """Register this mod with the router."""
        register_msg = {
            "type": "register",
            "mod_id": self.mod_id,
            "name": self.name,
            "capabilities": self.capabilities,
        }

        if not self.send_message(register_msg):
            return False

        response = self.receive_message()
        if response and response.get("type") == "registered":
            logger.info(f"Registered with router: {response}")
            return True

        logger.error(f"Registration failed: {response}")
        return False

    # =========================================================================
    # MESSAGE DISPATCH
    # =========================================================================

    def handle_message(self, message: Dict[str, Any]) -> Dict[str, Any]:
        """Route incoming messages to ``cmd_*`` handlers."""
        msg_type = message.get("type", "")
        msg_id = message.get("id", "")
        data = message.get("data", {})

        if msg_type == "command":
            command = data.get("command", "")
            args = data.get("args", {})

            handler = getattr(self, f"cmd_{command}", None)
            if handler:
                try:
                    result = handler(args)
                    return {
                        "id": msg_id,
                        "type": "response",
                        "success": True,
                        "data": result,
                    }
                except Exception as e:
                    logger.exception(f"Command {command} failed")
                    return {
                        "id": msg_id,
                        "type": "error",
                        "success": False,
                        "error": str(e),
                    }
            return {
                "id": msg_id,
                "type": "error",
                "success": False,
                "error": f"Unknown command: {command}",
            }

        if msg_type == "ping":
            return {"id": msg_id, "type": "pong"}

        return {
            "id": msg_id,
            "type": "error",
            "success": False,
            "error": f"Unknown message type: {msg_type}",
        }

    def send_update(self, update_type: str, data: Dict[str, Any]) -> bool:
        """Send a progress / status update to the GUI."""
        message = {
            "type": "mod_update",
            "mod_id": self.mod_id,
            "update_type": update_type,
            "data": data,
        }
        return self.send_message(message)

    # =========================================================================
    # MAIN LOOP
    # =========================================================================

    def run(self):
        """Connect, register, and handle messages until stopped."""
        self.running = True

        if not self.connect():
            logger.error("Could not connect to router. Is it running?")
            return

        if not self.register():
            logger.error("Registration failed")
            return

        logger.info(f"Mod '{self.name}' ready")

        try:
            while self.running:
                try:
                    message = self.receive_message()
                except socket.timeout:
                    continue  # No data yet — keep waiting

                if message is None:
                    logger.warning("Connection to router lost")
                    break

                response = self.handle_message(message)
                self.send_message(response)
        except Exception as e:
            logger.exception(f"Mod error: {e}")
        finally:
            if self._socket:
                try:
                    self._socket.close()
                except Exception:
                    pass
                self._socket = None
            logger.info("Mod stopped")
